#!/usr/bin/env python3
"""Asset generator for the positioning-message-house skill.

Reads house.json (schema: references/output-template.md) and emits battlecard.md and
objection-handling.md deterministically. Assets generated from the house cannot drift
from it: edit the house, regenerate, never edit the assets.

Usage:
  python3 generate_assets.py house.json [-o outdir]

No dependencies beyond the standard library. No network.
"""

import argparse
import json
import os

NOTICE = ("> Generated from `house.json` by `generate_assets.py`. Edit the house and "
          "regenerate; do not edit this file.\n")


def battlecard(h):
    bet = h.get("bet", {})
    lines = [f"# Battlecard: {h.get('brand', '?')}", "", NOTICE,
             "## The bet", "", bet.get("claim", ""), ""]
    if bet.get("metric"):
        lines += [f"**The metric that settles it:** {bet['metric']}", ""]

    lines += ["## Pillars", ""]
    for p in h.get("pillars", []):
        lines += [f"### {p.get('name', p.get('id', '?'))}", "", p.get("message", ""), ""]
        for proof in p.get("proof", []):
            lines.append(f"- {proof}")
        lines.append("")

    lines += ["## When we win", ""]
    lines += [f"- {w}" for w in h.get("when_we_win", [])]
    lines += ["", "## When we lose (say it before they do)", ""]
    lines += [f"- {w}" for w in h.get("when_we_lose", [])]

    lines += ["", "## Objections at a glance", "",
              "| Objection | Raised by | Response |", "|---|---|---|"]
    for o in h.get("objections", []):
        lines.append(f"| {o.get('objection', '')} | {o.get('from', '')} | "
                     f"{o.get('response', '')} |")
    lines.append("")
    return "\n".join(lines)


def objection_doc(h):
    pillars = {p.get("id"): p for p in h.get("pillars", [])}
    lines = [f"# Objection handling: {h.get('brand', '?')}", "", NOTICE]
    for o in h.get("objections", []):
        lines += [f"## \"{o.get('objection', '')}\"", "",
                  f"**Raised by:** {o.get('from', '?')}", "",
                  o.get("response", ""), ""]
        pillar = pillars.get(o.get("pillar"))
        if pillar:
            lines += [f"**Stands on:** {pillar.get('name')} ("
                      f"{pillar.get('message', '')})", ""]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description="Generate battlecard and objection doc from a message house.")
    ap.add_argument("house")
    ap.add_argument("-o", "--outdir", default=".")
    args = ap.parse_args()

    h = json.load(open(args.house, encoding="utf-8"))
    missing = [k for k in ("bet", "pillars", "when_we_lose", "objections") if not h.get(k)]
    if missing:
        raise SystemExit(f"house.json is missing required sections: {', '.join(missing)} "
                         "(when_we_lose is required: a battlecard that never loses is not believed)")

    for name, content in (("battlecard.md", battlecard(h)),
                          ("objection-handling.md", objection_doc(h))):
        path = os.path.join(args.outdir, name)
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
